apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelue-app
  labels:
    app: kelue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kelue-app
  template:
    metadata:
      labels:
        app: kelue-app
    spec:
      containers:
      - name: simple-node
        image: kelue/simple-node
        ports:
        - containerPort: 80